rules:

  block-closing-brace-newline-after: always
  block-no-empty: true
  block-opening-brace-newline-after: always
  block-opening-brace-space-before: always
  declaration-block-trailing-semicolon: always
  declaration-colon-space-after: always
  function-url-quotes: always
  length-zero-no-unit: true
  max-empty-lines: 1
  no-duplicate-selectors: true
  no-extra-semicolons: true
  number-leading-zero: never
  property-case: lower
  rule-empty-line-before: always
  selector-combinator-space-after: always
  selector-combinator-space-before: always
  selector-list-comma-newline-after: always
  selector-type-case: lower
  shorthand-property-no-redundant-values: true
  unit-case: lower
  no-eol-whitespace: true
  declaration-bang-space-before: always

  string-quotes: single
  declaration-block-no-duplicate-properties: true
  declaration-block-no-redundant-longhand-properties: true
  declaration-block-semicolon-newline-after: always
  function-calc-no-unspaced-operator: true
  media-feature-colon-space-after: always
  media-feature-name-case: lower
  media-query-list-comma-newline-after: always
  number-max-precision: 3
  selector-attribute-quotes: always

  indentation: 2

  comment-empty-line-before: always
  color-hex-case: lower
  max-nesting-depth: 3